-- Switch events.id from a uuid (gen_random_uuid()) to an auto-incrementing
-- integer. events was truncated in 0004 while repointing organiser_id/
-- coordinator_id, so there's no existing data to convert.
--
-- Guarded so this is safe to re-run if it partially applied before.

do $$
begin
  if (
    select data_type from information_schema.columns
    where table_name = 'events' and column_name = 'id'
  ) = 'uuid' then
    alter table events drop constraint if exists events_pkey;
    alter table events alter column id drop default;
    alter table events alter column id type integer using null;
    alter table events alter column id add generated by default as identity;
    alter table events add constraint events_pkey primary key (id);
  end if;
end
$$;
