-- E4 venue search: Coordinator filters venues by date/time, attendance,
-- location, capacity, accessibility, layout and facilities to shortlist
-- realistic options.
--
-- venues holds the searchable attributes. accessibility/layouts/facilities
-- are text[] rather than join tables: the filter is "venue has ALL of the
-- selected values", which is a single array-containment check, and the
-- option lists are small and descriptive rather than entities in their own
-- right. Values are stored as the display label ("Wheelchair access") so
-- the filter options can be derived straight from the table without a
-- separate lookup.
--
-- venue_bookings is what makes a venue unavailable for a date/time window
-- (AC2). booking_date/start_time/end_time mirror how events store their
-- schedule (proposedDate/startTime/endTime as a local date + times), so a
-- search pre-filled from an event compares like with like and no timezone
-- conversion is involved. event_id is optional: a booking may be for one
-- of our events, or an external hold/maintenance block.
--
-- Guarded so this is safe to re-run.

create table if not exists venues (
  id integer generated by default as identity primary key,
  name text not null,
  location text not null,
  description text,
  capacity integer not null check (capacity > 0),
  accessibility text[] not null default '{}',
  layouts text[] not null default '{}',
  facilities text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists venue_bookings (
  id bigserial primary key,
  venue_id integer not null references venues (id) on delete cascade,
  event_id integer references events (id) on delete set null,
  booking_date date not null,
  start_time time not null,
  end_time time not null,
  reason text,
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create index if not exists venue_bookings_venue_date_idx on venue_bookings (venue_id, booking_date);
create index if not exists venue_bookings_date_idx on venue_bookings (booking_date);

-- Same stance as users (0004): RLS on with no policies, so only the
-- backend's service-role key can reach these tables.
alter table venues enable row level security;
alter table venue_bookings enable row level security;
