-- E4 venue search: Coordinator filters venues by date/time, attendance,
-- location, capacity, accessibility, layout and facilities to shortlist
-- realistic options.
--
-- venues holds the searchable attributes. accessibility/layouts/facilities
-- are text[] rather than join tables: the filter is "venue has ALL of the
-- selected values", which is a single array-containment check, and the
-- option lists are small and descriptive rather than entities in their own
-- right. Values are stored as the display label ("Wheelchair access") so
-- the filter options can be derived straight from the table without a
-- separate lookup.
--
-- venues.status is the venue's own availability (Available = searchable and
-- bookable), and is not to be confused with the booking-approval enum
-- `venue_booking_status` on venue_bookings (migration 0014).
--
-- venue_bookings is what makes a venue unavailable for a date/time window
-- (AC2). It stores no timing of its own: a booking's date and times always
-- come from its linked event (events.submitted_details, read through
-- events-service's GET /venue-booking-info), so there is nothing to keep in
-- sync. event_id is therefore mandatory — there is no "external hold"
-- booking without an event.
--
-- Periods a venue is unavailable (maintenance, equipment failure,
-- renovation, safety) live in venue_unavailability, created by migration
-- 0016 — not here.
--
-- Guarded so this is safe to re-run.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'venue_availability_status') then
    create type venue_availability_status as enum ('Available', 'Unavailable');
  end if;
end
$$;

create table if not exists venues (
  id integer generated by default as identity primary key,
  name text not null,
  location text not null,
  description text,
  capacity integer not null check (capacity > 0),
  accessibility text[] not null default '{}',
  layouts text[] not null default '{}',
  facilities text[] not null default '{}',
  status venue_availability_status not null default 'Available',
  -- Still read by parts of the codebase that predate `status`; kept until
  -- they all move over.
  active boolean not null default true,
  -- Week 7 change 1: availability checks count these around each event.
  setup_minutes integer not null default 0 check (setup_minutes >= 0),
  turnaround_minutes integer not null default 0 check (turnaround_minutes >= 0),
  created_at timestamptz not null default now()
);

-- For databases created before these columns existed.
alter table venues add column if not exists status venue_availability_status not null default 'Available';
alter table venues add column if not exists active boolean not null default true;
alter table venues add column if not exists setup_minutes integer not null default 0;
alter table venues add column if not exists turnaround_minutes integer not null default 0;

-- `status` is the venue's own availability. The older `active` boolean is
-- deliberately left in place for now: part of the codebase still reads it,
-- so a venue taken out of use must be updated in both until everything
-- moves over to `status`.
update venues set status = 'Unavailable' where active = false;

-- Week 7 change 2 (venue unavailable after booking): the venue_unavailability
-- table is created in 0016_venue_unavailability.sql (E4-3). A period there
-- is a date range that either blocks whole days or the same hours on each
-- day, so "09:00–13:00 every day for a week" is one row.

create table if not exists venue_bookings (
  id bigserial primary key,
  venue_id integer not null references venues (id) on delete cascade,
  event_id integer not null references events (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- For databases created while a booking duplicated its event's timing: drop
-- those columns and their date indexes, remove the event-less "external
-- hold" rows, and require a real event. on delete cascade replaces the old
-- on delete set null, since a booking can't survive its event being deleted
-- without violating not null.
drop index if exists venue_bookings_venue_date_idx;
drop index if exists venue_bookings_date_idx;

alter table venue_bookings drop column if exists booking_date;
alter table venue_bookings drop column if exists start_time;
alter table venue_bookings drop column if exists end_time;
alter table venue_bookings drop column if exists reason;

delete from venue_bookings where event_id is null;

alter table venue_bookings drop constraint if exists venue_bookings_event_id_fkey;
alter table venue_bookings alter column event_id set not null;
alter table venue_bookings add constraint venue_bookings_event_id_fkey
  foreign key (event_id) references events (id) on delete cascade;

create index if not exists venue_bookings_venue_id_idx on venue_bookings (venue_id);

-- Same stance as users (0004): RLS on with no policies, so only the
-- backend's service-role key can reach these tables.
alter table venues enable row level security;
alter table venue_bookings enable row level security;
