-- E5-1: Record equipment requirements. New entity (per AGENTS.md §1,
-- "equipment" is the example given) owned by a new equipment-service.
--
-- equipment_requests is the Event Coordinator's request, one row per
-- submission for an event (an event may accumulate more than one, same as
-- venue_bookings allows several venues per event). status stays 'Requested'
-- until Technical Support update it (E5-3, #50) — "Requested", "Arranged"
-- or "Partially Fulfilled" — kept as plain text rather than a Postgres enum
-- since the API already validates it. fulfillment_note is E5-3 AC2's note
-- on what remains outstanding when only partly fulfilled.
--
-- equipment_request_items is the list of items per request — equipment
-- type and quantity, per AC1. quantity > 0 is enforced here too (AC3), not
-- just in the API, since the backend uses the service-role key and nothing
-- else stands between a bad row and the table. (The Coordinator's form no
-- longer collects technical requirements; a database that still carries
-- that column from before has a harmless, unused one — nothing reads it.)
--
-- Guarded so this is safe to re-run.

create table if not exists equipment_requests (
  id bigint generated by default as identity primary key,
  event_id integer not null references events (id) on delete cascade,
  coordinator_id text not null references users (id),
  status text not null default 'Requested',
  fulfillment_note text,
  created_at timestamptz not null default now()
);

create table if not exists equipment_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references equipment_requests (id) on delete cascade,
  equipment_type text not null,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

create index if not exists equipment_requests_event_idx on equipment_requests (event_id);
create index if not exists equipment_request_items_request_idx on equipment_request_items (request_id);

-- Same stance as every other table since migration 0004: RLS on with no
-- policies, so only the backend's service-role key can reach these.
alter table equipment_requests enable row level security;
alter table equipment_request_items enable row level security;
