-- Captures equipment/equipment_booking, which already exist in the live
-- dev database (made directly in Supabase Studio, same situation
-- migration 0014 documented for venue_bookings."Status") but were never
-- recorded in a migration file. Guarded so this is safe to re-run both
-- here and against the database that already has them.
--
-- These are early scaffolding for a future story (equipment availability
-- /reservation — E5-4/E5-6), separate from E5-1's equipment_requests
-- (migration 0020): a request is what a coordinator asks for, this is the
-- inventory it would eventually be checked and reserved against. Neither
-- table is read or written by any backend code yet.
--
-- Known rough edges, kept as-is here rather than silently "fixed" in a
-- migration meant to just capture current state — worth a look before
-- E5-4/E5-6 build on this:
--   - equipment.status reuses the *event* status enum (Planning, Safety
--     Review, Cancelled, ...), which doesn't describe an equipment row.
--   - Neither table has a quantity column, so representing "40 folding
--     tables" needs 40 rows, one per physical unit.

create table if not exists equipment (
  id bigint generated by default as identity primary key,
  type text not null,
  status event_status
);

create table if not exists equipment_booking (
  id bigint generated by default as identity primary key,
  equipment_id bigint references equipment (id),
  event_id integer references events (id),
  created_at timestamptz not null default now()
);

create index if not exists equipment_booking_equipment_idx on equipment_booking (equipment_id);
create index if not exists equipment_booking_event_idx on equipment_booking (event_id);

-- Same stance as every other table since migration 0004: RLS on with no
-- policies, so only the backend's service-role key can reach these.
alter table equipment enable row level security;
alter table equipment_booking enable row level security;
