-- E5-1/E5-3 stock tracking: Technical Support need to see how much of each
-- equipment type is actually available, not just the free-text requests
-- coming in. equipment_catalog is the fixed list Coordinators now pick
-- from (replacing the old free-text equipment_type input) and the stock
-- counter Technical Support's view shows alongside incoming requests.
--
-- available_stock only moves when Technical Support act on a request
-- (Requested itself reserves nothing): marking a request "Arranged" takes
-- the full requested quantity off the shelf, "Partially Fulfilled" takes
-- only what was actually handed out (recorded per item below), and moving
-- a request back to an earlier status returns whatever was taken. See
-- apply_equipment_request_status() below for the single place this math
-- happens.
--
-- Guarded so this is safe to re-run.

create table if not exists equipment_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique,
  total_stock integer not null default 0 check (total_stock >= 0),
  available_stock integer not null default 0 check (available_stock >= 0 and available_stock <= total_stock),
  created_at timestamptz not null default now()
);

alter table equipment_catalog enable row level security;

-- Per-item link to the catalog (for stock math) and how much of that item
-- is currently taken off the shelf under the request's current status.
-- Nullable: rows recorded before this migration have no catalog entry and
-- simply never participate in stock tracking.
alter table equipment_request_items add column if not exists equipment_catalog_id bigint references equipment_catalog (id);
alter table equipment_request_items add column if not exists quantity_fulfilled integer not null default 0 check (quantity_fulfilled >= 0);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'equipment_request_items_fulfilled_le_quantity'
  ) then
    alter table equipment_request_items
      add constraint equipment_request_items_fulfilled_le_quantity check (quantity_fulfilled <= quantity);
  end if;
end
$$;

create index if not exists equipment_request_items_catalog_idx on equipment_request_items (equipment_catalog_id);

-- Single place a request's status (and the stock it holds) changes.
-- Recomputes each item's quantity_fulfilled for the target status and
-- applies only the delta to equipment_catalog.available_stock, so moving
-- back and forth between statuses (e.g. Arranged -> Partially Fulfilled ->
-- Requested) always nets out correctly. p_fulfillments is only consulted
-- for 'Partially Fulfilled': a jsonb array of {"itemId": ..., "fulfilledQuantity": ...}.
-- Runs in the caller's transaction (PostgREST wraps each request in one),
-- so any raised exception rolls the whole update back — a request never
-- ends up with a status that doesn't match what was actually taken off
-- the shelf.
create or replace function apply_equipment_request_status(
  p_request_id bigint,
  p_status text,
  p_note text,
  p_fulfillments jsonb default '[]'::jsonb
)
returns void
language plpgsql
as $$
declare
  item record;
  target_fulfilled integer;
  delta integer;
  available integer;
begin
  if p_status not in ('Requested', 'Arranged', 'Partially Fulfilled') then
    raise exception 'Invalid status: %', p_status;
  end if;

  if not exists (select 1 from equipment_requests where id = p_request_id for update) then
    raise exception 'Equipment request not found: %', p_request_id;
  end if;

  for item in
    select id, quantity, quantity_fulfilled, equipment_catalog_id
    from equipment_request_items
    where request_id = p_request_id
    order by equipment_catalog_id, id
  loop
    if p_status = 'Requested' then
      target_fulfilled := 0;
    elsif p_status = 'Arranged' then
      target_fulfilled := item.quantity;
    else
      select (elem->>'fulfilledQuantity')::integer into target_fulfilled
      from jsonb_array_elements(p_fulfillments) elem
      where (elem->>'itemId')::bigint = item.id;

      if target_fulfilled is null then
        raise exception 'Missing fulfilled quantity for item %', item.id;
      end if;
      if target_fulfilled < 0 or target_fulfilled > item.quantity then
        raise exception 'Fulfilled quantity for item % must be between 0 and %', item.id, item.quantity;
      end if;
    end if;

    delta := target_fulfilled - coalesce(item.quantity_fulfilled, 0);

    if delta <> 0 and item.equipment_catalog_id is not null then
      select available_stock into available
        from equipment_catalog where id = item.equipment_catalog_id
        for update;

      if delta > 0 and available < delta then
        raise exception 'Not enough stock available for item %', item.id;
      end if;

      update equipment_catalog
        set available_stock = available_stock - delta
        where id = item.equipment_catalog_id;
    end if;

    update equipment_request_items
      set quantity_fulfilled = target_fulfilled
      where id = item.id;
  end loop;

  update equipment_requests
    set status = p_status, fulfillment_note = p_note
    where id = p_request_id;
end;
$$;
