-- E6: Attendee registration for an event. New entity, owned by the new
-- registration-service (AGENTS.md §1). One row per attendee per event.
--
-- status is the Postgres enum registration_status: 'Registered' while the
-- attendee holds a place, 'Withdrawn' once they give it up. The row stays
-- for history rather than being deleted, so re-registering later means
-- setting the same row back to 'Registered' (the unique constraint allows
-- only one row per attendee per event).
-- additional_info is optional free-form JSON (e.g. answers to a
-- registration form); null when the attendee supplied nothing.
--
-- Guarded so this is safe to re-run.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'registration_status') then
    create type registration_status as enum ('Registered', 'Withdrawn');
  end if;
end
$$;

create table if not exists registrations (
  registration_id bigint generated by default as identity primary key,
  event_id integer not null references events (id) on delete cascade,
  user_id text not null references users (id) on delete cascade,
  status registration_status not null default 'Registered',
  created_at timestamptz not null default now(),
  additional_info jsonb,
  constraint registrations_event_user_unique unique (event_id, user_id)
);

create index if not exists registrations_user_idx on registrations (user_id);

-- Same stance as every other table since migration 0004: RLS on with no
-- policies, so only the backend's service-role key can reach this.
alter table registrations enable row level security;
