-- E2-15: a live chat between an Organiser and their event's assigned
-- coordinator, owned by a new chat-service (AGENTS.md §1: a new domain
-- entity gets a new microservice — this is distinct from
-- event_clarifications, which is a status-gated, coordinator-initiated
-- Q&A thread baked into the review lifecycle, not a free-flowing chat).
--
-- One thread per event: event_id is the thread, so there is no separate
-- chat_threads table. Both parties for a thread are already on the event
-- row (organiser_id, coordinator_id) and read live through events-service,
-- never duplicated here.
--
-- read_at works the same way notifications.read_at does: a message has
-- exactly one recipient (the other party on a 1:1 thread), so a single
-- column is enough to track whether they've opened the thread since it
-- arrived — no separate per-recipient table needed.
--
-- A message requires a coordinator to already be assigned (chat-service
-- enforces this, not a constraint here, since it also needs to apply the
-- "event reached a terminal status" send-block, which isn't expressible as
-- a static check against this table alone).
--
-- Guarded so this is safe to re-run.

create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  event_id integer not null references events (id) on delete cascade,
  sender_id text not null references users (id),
  sender_role text not null check (sender_role in ('organiser', 'coordinator')),
  body text not null check (length(btrim(body)) > 0),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_event_created_idx on chat_messages (event_id, created_at);

-- Same stance as every other table since migration 0004: RLS on with no
-- policies, so only the backend's service-role key can reach it.
alter table chat_messages enable row level security;
